#
# "main" pseudo-component makefile.
#
# (Uses default behaviour of compiling all source files in directory, adding 'include' to include path.)

ifdef CONFIG_OPERATION_UART_PORT
CPPFLAGS += -DCONFIG_OPERATION_UART_PORT=$(CONFIG_OPERATION_UART_PORT)
endif

ifdef CONFIG_UART1_PIN_4_5
CPPFLAGS += -DCONFIG_UART1_PIN_4_5=$(CONFIG_UART1_PIN_4_5)
endif

ifdef CONFIG_CPC_ENABLE_ZIGBEE_NCP
CPPFLAGS += -DCONFIG_CPC_ENABLE_ZIGBEE_NCP=$(CONFIG_CPC_ENABLE_ZIGBEE_NCP)
endif

ifdef CONFIG_ENABLE_3W_PTA
CPPFLAGS += -DCONFIG_ENABLE_3W_PTA=$(CONFIG_ENABLE_3W_PTA)
endif

ifdef CONFIG_TX_POWER_SET
CPPFLAGS += -DCONFIG_TX_POWER_SET=$(CONFIG_TX_POWER_SET)
endif

ifdef CONFIG_CPC_RX_PAYLOAD_MAX_LENGTH
CPPFLAGS += -DCPC_RX_PAYLOAD_MAX_LENGTH=$(CONFIG_CPC_RX_PAYLOAD_MAX_LENGTH)
endif

ifdef CONFIG_CPC_OPERATION_BAUDRATE
CPPFLAGS += -DCPC_OPERATION_BAUDRATE=$(CONFIG_CPC_OPERATION_BAUDRATE)
endif

ifdef CONFIG_CPC_OPERARION_UART_PIN_1
CPPFLAGS += -DCPC_OPERARION_UART_PIN_1=$(CONFIG_CPC_OPERARION_UART_PIN_1)
endif

ifdef CONFIG_CPC_OPERARION_UART_PIN_2
CPPFLAGS += -DCPC_OPERARION_UART_PIN_2=$(CONFIG_CPC_OPERARION_UART_PIN_2)
endif
COMPONENT_ADD_INCLUDEDIRS += Include
