#
#compiler flag config domain
#

CONFIG_SYS_APP_TASK_STACK_SIZE:=512
CONFIG_SYS_APP_TASK_PRIORITY:=15
CONFIG_CLI_CMD_ENABLE:=1
CONFIG_LOG_ENABLED_COMPONENTS:=multi_protocol_rcp
CONFIG_HOSAL_RF_DEBUG:=0
CONFIG_OPENTHREAD_TASK_SIZE:=512

CONFIG_ENABLE_3W_PTA:=0
# CONFIG_CPC_OPERARION_UART_PIN_1:=28
# CONFIG_CPC_OPERARION_UART_PIN_2:=29
# CONFIG_CPC_OPERATION_BAUDRATE:=2000000
# CONFIG_CPC_OPERATION_BAUDRATE:=1000000
# CONFIG_CPC_OPERATION_BAUDRATE:=500000
# CONFIG_CPC_OPERATION_BAUDRATE:=115200
